[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core = "0.3.28"
http = "0.2.9"
prost = "0.12.1"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.10.1"
tonic-web = "0.10.1"
tower-http = { version = "0.4.4", default-features = false, features = [
    "cors",
] }

[build-dependencies]
tonic-build = "0.10.1"
