name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: wasm32-unknown-unknown
          - target: wasm32-wasip2
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Rust from rust-toolchain.toml
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }}
  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Rust from rust-toolchain.toml
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: wasm32-unknown-unknown
          - target: wasm32-wasip2
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Rust from rust-toolchain.toml
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target }} -- -D warnings
